# Generated by Django 4.2.7 on 2023-11-25 19:16

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Title must be at least 8 characters long.')]),
        ),
    ]
